name: Danger
on: 
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
